# UNDERSTANDING THE DATASETS
## Data Cleaning

In [6]:
import pandas as pd
s=pd.read_csv("Data/PEMS-BAY-META.csv")
s

,sensor_id,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
0,400649,17,N,4,85,44112.0,9.06,21.613,37.251741,-121.958118,0.850,ML,2,LARK AVE,DT185,L2-N-37-017-00906,998009,417770
1,400715,17,N,4,85,44112.0,9.4,21.953,37.256205,-121.955355,0.245,ML,2,SB 85 rm-n-conn,DT244,L2-N-37-017-00940,998013,417774
2,400240,17,N,4,85,44112.0,9.55,22.103,37.258184,-121.953853,0.535,ML,3,NB 85 rm-n-conn,DT260,L3-N-37-017-00955,998017,420767
3,403329,17,N,4,85,10340.0,10.47,23.023,37.270267,-121.947353,0.510,ML,3,Camden ave rm-n-loop,DTB25,L3-N-37-017-01047,997278,430594
4,400436,17,N,4,85,10340.0,10.57,23.123,37.271687,-121.947037,0.905,ML,3,Camden Ave rm-n-diag,DT267,l3-N-37-017-01057,998021,420772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,400973,237,E,4,85,69084.0,6.18,6.237,37.417801,-121.972288,0.973,ML,3,GREAT AMERICA PKWY,DT852,L3-E-37-237-00618,998245,420562
321,400567,237,E,4,85,68000.0,6.7,6.752,37.418931,-121.962821,0.462,ML,4,N First St,DT193,L4-E-37-237-00670,998232,420414
322,400104,237,E,4,85,68000.0,7.11,7.162,37.419313,-121.955480,0.665,ML,3,NORTH FIRST STREET,DT814,L3-E-37-237-00711,998233,420567
323,400296,237,E,4,85,68000.0,8.03,8.082,37.420359,-121.939150,0.530,ML,3,oppo Zanker Rd rm-w-loop,DT822,L3-E-37-237-00803,998236,420572
324,400873,237,E,4,85,68000.0,8.17,8.222,37.420927,-121.936740,2.570,ML,3,ZANKER RD,DT834,L3-E-37-237-00817,998237,420577

In [7]:
s.head(10)

,sensor_id,Fwy,Dir,District,County,City,State_PM,Abs_PM,Latitude,Longitude,Length,Type,Lanes,Name,User_ID_1,User_ID_2,User_ID_3,User_ID_4
0,400649,17,N,4,85,44112.0,9.06,21.613,37.251741,-121.958118,0.850,ML,2,LARK AVE,DT185,L2-N-37-017-00906,998009,417770
1,400715,17,N,4,85,44112.0,9.4,21.953,37.256205,-121.955355,0.245,ML,2,SB 85 rm-n-conn,DT244,L2-N-37-017-00940,998013,417774
2,400240,17,N,4,85,44112.0,9.55,22.103,37.258184,-121.953853,0.535,ML,3,NB 85 rm-n-conn,DT260,L3-N-37-017-00955,998017,420767
3,403329,17,N,4,85,10340.0,10.47,23.023,37.270267,-121.947353,0.510,ML,3,Camden ave rm-n-loop,DTB25,L3-N-37-017-01047,997278,430594
4,400436,17,N,4,85,10340.0,10.57,23.123,37.271687,-121.947037,0.905,ML,3,Camden Ave rm-n-diag,DT267,l3-N-37-017-01057,998021,420772
5,400221,17,N,4,85,10340.0,12.28,24.833,37.293614,-121.937899,0.945,ML,3,Hamilton Ave rm-n-loop,DT754,L3-N-37-017-01228,998025,420777
6,404370,17,N,4,85,10340.0,12.46,25.013,37.296028,-121.939132,1.579,ML,4,Hamilton Ave rm-n-diag,DT909,L4-N-37-017-01246,998029,422458
7,400268,85,N,4,85,68000.0,5.18,5.180,37.255651,-121.858078,0.600,ML,3,SANTA TERESA,DT488,L3-N-37-085-00518,998053,420812
8,401555,85,N,4,85,68000.0,5.23,5.230,37.255657,-121.858984,0.480,ML,3,Santa Teresa rm-n-diag,DT973,L3-N-37-085-00523,998998,420817
9,400052,85,N,4,85,68000.0,6.14,6.140,37.255791,-121.875479,0.555,ML,3,Almaden Expwy,DT490,L3-N-37-085-00614,998057,420822

In [8]:
print(s.shape)

(325, 18)

In [9]:
print(s.columns)

Index(['sensor_id', 'Fwy', 'Dir', 'District', 'County', 'City', 'State_PM',
       'Abs_PM', 'Latitude', 'Longitude', 'Length', 'Type', 'Lanes', 'Name',
       'User_ID_1', 'User_ID_2', 'User_ID_3', 'User_ID_4'],
      dtype='str')

In [10]:
import h5py
with h5py.File("Data/pems-bay.h5") as f:
    print(list(f.keys()))

['speed']

In [11]:
import h5py

with h5py.File("Data/pems-bay.h5", "r") as f:
    speed = f["speed"]

    print("Inside speed:")
    print(list(speed.keys()))

Inside speed:
['axis0', 'axis1', 'block0_items', 'block0_values']

In [12]:
with h5py.File("Data/pems-bay.h5", "r") as f:
    speed = f["speed"]

    for name in speed.keys():
        print(name, speed[name].shape, speed[name].dtype)

axis0 (325,) int64
axis1 (52116,) int64
block0_items (325,) int64
block0_values (52116, 325) float64

In [13]:
with h5py.File("Data/pems-bay.h5", "r") as f:
    speed = f["speed"]

    for name in speed.keys():
        print(name)
        print("shape:", speed[name].shape)
        print("type:", type(speed[name]))
        print()

axis0
shape: (325,)
type: <class 'h5py._hl.dataset.Dataset'>

axis1
shape: (52116,)
type: <class 'h5py._hl.dataset.Dataset'>

block0_items
shape: (325,)
type: <class 'h5py._hl.dataset.Dataset'>

block0_values
shape: (52116, 325)
type: <class 'h5py._hl.dataset.Dataset'>

In [14]:
with h5py.File("Data/pems-bay.h5", "r") as f:
    speed = f["speed"]["block0_values"]

    print(speed[:10, :10])

[[71.4 67.8 70.5 67.4 68.8 66.6 66.8 68.  66.8 69. ]
 [71.6 67.5 70.6 67.5 68.7 66.6 66.8 67.8 66.5 68.2]
 [71.6 67.6 70.2 67.4 68.7 66.1 66.8 67.8 66.2 67.8]
 [71.1 67.5 70.3 68.  68.5 66.7 66.6 67.7 65.9 67.8]
 [71.7 67.8 70.2 68.1 68.4 66.9 66.1 67.7 66.1 67.8]
 [71.2 67.4 70.3 67.5 68.4 66.5 65.3 67.8 66.4 68.1]
 [71.3 67.6 70.1 67.2 68.5 66.8 65.7 67.8 66.7 68.4]
 [70.5 67.6 70.6 68.1 68.4 66.4 66.6 67.8 66.3 68.4]
 [71.5 67.5 70.5 67.6 68.3 66.5 66.4 67.8 66.6 68.3]
 [70.7 67.4 70.5 68.3 68.5 66.1 66.5 67.8 66.7 68.4]]

In [15]:
with h5py.File("Data/pems-bay.h5", "r") as f:
    axis0 = f["speed"]["axis0"][:]

    print(axis0[:20])

[400001 400017 400030 400040 400045 400052 400057 400059 400065 400069
 400073 400084 400085 400088 400096 400097 400100 400104 400109 400122]

### *Details Of The Sensors*

In [16]:
with h5py.File("Data/pems-bay.h5","r") as f:
    axis0 = f["speed"]["axis0"]

    print(axis0[:20])

[400001 400017 400030 400040 400045 400052 400057 400059 400065 400069
 400073 400084 400085 400088 400096 400097 400100 400104 400109 400122]

#### *UNIX TIMESTAMPS*

In [17]:
with h5py.File("Data/pems-bay.h5", "r") as f:
    axis1 = f["speed"]["axis1"][:]

    print(axis1[:20])

[1483228800000000000 1483229100000000000 1483229400000000000
 1483229700000000000 1483230000000000000 1483230300000000000
 1483230600000000000 1483230900000000000 1483231200000000000
 1483231500000000000 1483231800000000000 1483232100000000000
 1483232400000000000 1483232700000000000 1483233000000000000
 1483233300000000000 1483233600000000000 1483233900000000000
 1483234200000000000 1483234500000000000]

In [18]:
print(1483228800000000000 - 1483229100000000000 )

-300000000000

In [19]:
import pandas as pd
with h5py.File("Data/pems-bay.h5","r") as f:
    timestamps = f["speed"]["axis1"][:]

dates = pd.to_datetime(timestamps)
print(dates)

DatetimeIndex(['2017-01-01 00:00:00', '2017-01-01 00:05:00',
               '2017-01-01 00:10:00', '2017-01-01 00:15:00',
               '2017-01-01 00:20:00', '2017-01-01 00:25:00',
               '2017-01-01 00:30:00', '2017-01-01 00:35:00',
               '2017-01-01 00:40:00', '2017-01-01 00:45:00',
               ...
               '2017-06-30 23:10:00', '2017-06-30 23:15:00',
               '2017-06-30 23:20:00', '2017-06-30 23:25:00',
               '2017-06-30 23:30:00', '2017-06-30 23:35:00',
               '2017-06-30 23:40:00', '2017-06-30 23:45:00',
               '2017-06-30 23:50:00', '2017-06-30 23:55:00'],
              dtype='datetime64[ns]', length=52116, freq=None)

In [20]:
print(dates[0])

2017-01-01 00:00:00

In [21]:
print(dates[-1])

2017-06-30 23:55:00

In [22]:
import h5py

with h5py.File("Data/pems-bay.h5", "r") as f:
    sensor_ids = f["speed"]["axis0"][:]

print(sensor_ids[:10])

[400001 400017 400030 400040 400045 400052 400057 400059 400065 400069]

In [23]:
print(s["sensor_id"].isin(sensor_ids).sum())
print(len(sensor_ids))

325
325

In [24]:
print(s.columns)

Index(['sensor_id', 'Fwy', 'Dir', 'District', 'County', 'City', 'State_PM',
       'Abs_PM', 'Latitude', 'Longitude', 'Length', 'Type', 'Lanes', 'Name',
       'User_ID_1', 'User_ID_2', 'User_ID_3', 'User_ID_4'],
      dtype='str')

In [25]:
s.shape[0]

325

In [26]:
import h5py
with h5py.File('Data/pems-bay.h5','r') as f:
    speed = f["speed"]["block0_values"][:]
    sensor_ids = f["speed"]["axis0"][:]
    timestamps = f["speed"]["axis1"][:]
print("Speed shape:", speed.shape)
print("Sensors:", len(sensor_ids))
print("Time steps:", len(timestamps))

Speed shape: (52116, 325)
Sensors: 325
Time steps: 52116

In [27]:
with h5py.File("Data/pems-bay.h5", "r") as f:

    print("=== SENSOR IDs ===")
    print(f["speed"]["axis0"][:10])

    print("\n=== TIMESTAMPS ===")
    print(f["speed"]["axis1"][:10])

    print("\n=== TRAFFIC SPEEDS ===")
    print(f["speed"]["block0_values"][:10, :10])

=== SENSOR IDs ===
[400001 400017 400030 400040 400045 400052 400057 400059 400065 400069]

=== TIMESTAMPS ===
[1483228800000000000 1483229100000000000 1483229400000000000
 1483229700000000000 1483230000000000000 1483230300000000000
 1483230600000000000 1483230900000000000 1483231200000000000
 1483231500000000000]

=== TRAFFIC SPEEDS ===
[[71.4 67.8 70.5 67.4 68.8 66.6 66.8 68.  66.8 69. ]
 [71.6 67.5 70.6 67.5 68.7 66.6 66.8 67.8 66.5 68.2]
 [71.6 67.6 70.2 67.4 68.7 66.1 66.8 67.8 66.2 67.8]
 [71.1 67.5 70.3 68.  68.5 66.7 66.6 67.7 65.9 67.8]
 [71.7 67.8 70.2 68.1 68.4 66.9 66.1 67.7 66.1 67.8]
 [71.2 67.4 70.3 67.5 68.4 66.5 65.3 67.8 66.4 68.1]
 [71.3 67.6 70.1 67.2 68.5 66.8 65.7 67.8 66.7 68.4]
 [70.5 67.6 70.6 68.1 68.4 66.4 66.6 67.8 66.3 68.4]
 [71.5 67.5 70.5 67.6 68.3 66.5 66.4 67.8 66.6 68.3]
 [70.7 67.4 70.5 68.3 68.5 66.1 66.5 67.8 66.7 68.4]]

### TRYING TO MAP THE SENSORS IDS TO THE TRAFFIC SPEEDS

In [28]:
with h5py.File("Data/pems-bay.h5","r") as f:
    print("===Sensor_id====")
    print(f["speed"]["axis1"][:10])
    print(f["speed"]["block0_values"][:10, :10])

===Sensor_id====
[1483228800000000000 1483229100000000000 1483229400000000000
 1483229700000000000 1483230000000000000 1483230300000000000
 1483230600000000000 1483230900000000000 1483231200000000000
 1483231500000000000]
[[71.4 67.8 70.5 67.4 68.8 66.6 66.8 68.  66.8 69. ]
 [71.6 67.5 70.6 67.5 68.7 66.6 66.8 67.8 66.5 68.2]
 [71.6 67.6 70.2 67.4 68.7 66.1 66.8 67.8 66.2 67.8]
 [71.1 67.5 70.3 68.  68.5 66.7 66.6 67.7 65.9 67.8]
 [71.7 67.8 70.2 68.1 68.4 66.9 66.1 67.7 66.1 67.8]
 [71.2 67.4 70.3 67.5 68.4 66.5 65.3 67.8 66.4 68.1]
 [71.3 67.6 70.1 67.2 68.5 66.8 65.7 67.8 66.7 68.4]
 [70.5 67.6 70.6 68.1 68.4 66.4 66.6 67.8 66.3 68.4]
 [71.5 67.5 70.5 67.6 68.3 66.5 66.4 67.8 66.6 68.3]
 [70.7 67.4 70.5 68.3 68.5 66.1 66.5 67.8 66.7 68.4]]

In [ ]:
from sklearn.model_selection import train_test_split
with h5py.File("Data/pems-bay.h5","r") as f:
    
    X = f["speed"]["axis1"][:10]
    

X_train,X_test,y_train,y_test = train_test_split()

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
speed_scaled = scaler.fit_transform